set SCHNITTFEST_HOST=localhost:8080
set SCHNITTFEST_LOGLEVEL=debug
set SCHNITTFEST_ALLOWED_ORIGINS=*
set SCHNITTFEST_TLS_ENABLE=false
set SCHNITTFEST_DISABLE_CACHE=true
set SCHNITTFEST_HOT_RELOAD=true

go run main.go
